version: 1.3.0.{build}
branches:
  only:
    - master
skip_tags: true
max_jobs: 1
configuration: Release
platform: x86
clone_depth: 50
image: Visual Studio 2019
before_build:
- ps: ./update-libraries.ps1
- cmd: nuget restore
build:
  project: Shamanic.sln
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(appveyor_build_version)'
after_build:
  7z a Shamanic.zip "%APPVEYOR_BUILD_FOLDER%\Shamanic\bin\x86\Release\Shamanic.dll"
artifacts:
  - path: Shamanic.zip
    name: Shamanic
