//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shamanic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shamanic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Display.
        /// </summary>
        internal static string CounterTitle {
            get {
                return ResourceManager.GetString("CounterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string DisplayModeAlways {
            get {
                return ResourceManager.GetString("DisplayModeAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string DisplayModeCard {
            get {
                return ResourceManager.GetString("DisplayModeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string DisplayModeClass {
            get {
                return ResourceManager.GetString("DisplayModeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string DisplayModeNever {
            get {
                return ResourceManager.GetString("DisplayModeNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        internal static string DisplayModeShaman {
            get {
                return ResourceManager.GetString("DisplayModeShaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost
        ///Spells.
        /// </summary>
        internal static string FrostSpellsEffectName {
            get {
                return ResourceManager.GetString("FrostSpellsEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost Spells.
        /// </summary>
        internal static string FrostSpellsTitle {
            get {
                return ResourceManager.GetString("FrostSpellsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always - Display Frost Spells cast for all games playing as any class.
        ///Shaman - Display Frost Spells cast when playing as Shaman.
        ///Class - Display Frost Spells cast when playing as Shaman/Rogue/Priest.
        ///Card - Display Frost Spells cast for &apos;Bearon Gla&apos;shear&apos;.
        ///Never - Do not display..
        /// </summary>
        internal static string FrostSpellsTooltip {
            get {
                return ResourceManager.GetString("FrostSpellsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overload &amp; Totems.
        /// </summary>
        internal static string OpponentDisplay {
            get {
                return ResourceManager.GetString("OpponentDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        internal static string OpponentTitle {
            get {
                return ResourceManager.GetString("OpponentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always - Display opponent Overload and Totems for all games vs any class.
        ///Shaman -  Display opponent Overload and Totems for all games vs Shaman.
        ///Class -  Display opponent Overload and Totems for all games vs Shaman/Rogue/Priest.
        ///Never - Do not display..
        /// </summary>
        internal static string OpponentTooltip {
            get {
                return ResourceManager.GetString("OpponentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overload
        ///Played.
        /// </summary>
        internal static string OverloadPlayedEffectName {
            get {
                return ResourceManager.GetString("OverloadPlayedEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overload Played.
        /// </summary>
        internal static string OverloadPlayedTitle {
            get {
                return ResourceManager.GetString("OverloadPlayedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always - Display Overload for all games playing as any class.
        ///Shaman - Display Overload when playing as Shaman.
        ///Class - Display Overload when playing as Shaman/Rogue/Priest.
        ///Card - Display Overload for &apos;Charged Call&apos;.
        ///Never - Do not display..
        /// </summary>
        internal static string OverloadPlayedTooltip {
            get {
                return ResourceManager.GetString("OverloadPlayedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overload
        ///Total.
        /// </summary>
        internal static string OverloadTotalEffectName {
            get {
                return ResourceManager.GetString("OverloadTotalEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overload Total.
        /// </summary>
        internal static string OverloadTotalTitle {
            get {
                return ResourceManager.GetString("OverloadTotalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always - Display Overload for all games playing as any class.
        ///Shaman - Display Overload when playing as Shaman.
        ///Class - Display Overload when playing as Shaman/Rogue/Priest.
        ///Card - Display Overload for &apos;Snowfury Giant&apos;.
        ///Never - Do not display..
        /// </summary>
        internal static string OverloadTotalTooltip {
            get {
                return ResourceManager.GetString("OverloadTotalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string PlayerTitle {
            get {
                return ResourceManager.GetString("PlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PluginButtonText {
            get {
                return ResourceManager.GetString("PluginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays total mana crystals overloaded and totems played for both the player and opponent.
        ///
        ///Mainly for use with the Shaman cards &apos;Thing from Below&apos; and &apos;Snowfury Giant&apos;.
        ///
        ///**WARNING** Disabling the plugin during a game will reset the counters..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SettingsDisplayTitle {
            get {
                return ResourceManager.GetString("SettingsDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string SettingsHorizontal {
            get {
                return ResourceManager.GetString("SettingsHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Screen Position (Left &lt;-&gt; Right).
        /// </summary>
        internal static string SettingsHorizontalTooltip {
            get {
                return ResourceManager.GetString("SettingsHorizontalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string SettingsOrientation {
            get {
                return ResourceManager.GetString("SettingsOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical or Horizontal view stacking.
        /// </summary>
        internal static string SettingsOrientationDescription {
            get {
                return ResourceManager.GetString("SettingsOrientationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string SettingsOrientationHorizontal {
            get {
                return ResourceManager.GetString("SettingsOrientationHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string SettingsOrientationVertical {
            get {
                return ResourceManager.GetString("SettingsOrientationVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string SettingsPositionResetButton {
            get {
                return ResourceManager.GetString("SettingsPositionResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string SettingsPositionTitle {
            get {
                return ResourceManager.GetString("SettingsPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shamanic Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string SettingsVertical {
            get {
                return ResourceManager.GetString("SettingsVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Screen Position (Top &lt;-&gt; Bottom).
        /// </summary>
        internal static string SettingsVerticalTooltip {
            get {
                return ResourceManager.GetString("SettingsVerticalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totems
        ///Played.
        /// </summary>
        internal static string TotemsPlayedEffectName {
            get {
                return ResourceManager.GetString("TotemsPlayedEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totems Played.
        /// </summary>
        internal static string TotemsPlayedTitle {
            get {
                return ResourceManager.GetString("TotemsPlayedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always - Display Totems for all games playing as any class.
        ///Shaman - Display Totems when playing as Shaman.
        ///Class - Display Totems when playing as Shaman/Rogue/Priest.
        ///Card - Display Totems for &apos;Thing from Below&apos; and/or &apos;Gigantotem&apos;.
        ///Never - Do not display..
        /// </summary>
        internal static string TotemsPlayedTooltip {
            get {
                return ResourceManager.GetString("TotemsPlayedTooltip", resourceCulture);
            }
        }
    }
}
